name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Increment version
        id: increment_version
        run: |
          # Extract the current version
          current_version=$(jq -r '.version' module.json)
          
          # Increment the version
          new_version=$((current_version + 1))
          
          # Update the module.json with the new version
          jq --arg new_version "$new_version" '.version = $new_version' module.json > module.tmp && mv module.tmp module.json
          
          echo "tag=v$new_version" >> $GITHUB_OUTPUT

      - name: Configure git user from GitHub token
        id: git-author
        uses: MarcoIeni/git-config@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Utilizing the GitHub token
        run: |
          git add module.json
          git commit -m "Increment version to $new_version"
          git push

      - name: Prepare files for artifact
        run: |
          mkdir -pv build-artifact
          rsync -av --progress ./ ./build-artifact --exclude .git --exclude .github --exclude .gitignore --exclude .idea --exclude *.iml
        shell: bash

      - name: Upload the files as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: dsa-hausregeln.zip
          path: build-artifact

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: dsa-hausregeln.zip
          path: .

      - name: ls
        run: |
          echo $GITHUB_WORKSPACE
          ls -alh $GITHUB_WORKSPACE

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: 'dsa-hausregeln.zip'
          tag_name: "${{steps.increment_version.outputs.tag}}"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: 'dsa-hausregeln.zip'


#      - name: download artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: dsa-hausregeln.zip
#
#      - name: ls
#        run: ls -alh
#
#      - name: Upload ZIP to Release
#        uses: actions/upload-release-asset@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          upload_url: ${{ steps.create_release.outputs.upload_url }}
#          asset_path: dsa-hausregeln.zip
#          asset_name: dsa-hausregeln.zip
#          asset_content_type: application/zip


# semi works
#      - name: Create a Release
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: ./dsa-hausregeln.zip
#          allowUpdates: true
#          makeLatest: true
#          name: Latest release
#          tag: latest
