name: Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Increment version
        id: increment_version
        run: |
          # Extract the current version
          current_version=$(jq -r '.version' module.json)
          
          # Increment the version
          new_version=$((current_version + 1))
          
          # Update the module.json with the new version
          jq --arg new_version "$new_version" '.version = $new_version' module.json > module.tmp && mv module.tmp module.json
          
          echo "tag=v$new_version" >> $GITHUB_OUTPUT

      - name: Configure git user from GitHub token
        id: git-author
        uses: MarcoIeni/git-config@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Utilizing the GitHub token
        run: |
          git add module.json
          git commit -m "Increment version to $new_version"
          git push

      - name: bundle
        run: |
          mkdir -pv build-artifact
          rsync -av --progress ./ ./build-artifact --exclude .git --exclude .github --exclude .gitignore --exclude .idea --exclude *.iml --exclude ./build-artifact
          cd ./build-artifact
          zip -r ../dsa-hausregeln.zip ./*
        shell: bash

      - name: Upload the files as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: dsa-hausregeln.zip
          path: build-artifact

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: 'dsa-hausregeln.zip'
          tag_name: "${{steps.increment_version.outputs.tag}}"
